const selectOptions = {
  type: [
    { name: "المقبوضات المالية", value: "المقبوضات المالية" },
    { name: "المدفوعات المالية", value: "المدفوعات المالية" },
  ],

  gender: [
    { name: "ذكر", value: "ذكر" },
    { name: "انثى", value: "انثى" },
  ],
  boolGender: [
    { name: "ذكر", value: true },
    { name: "انثى", value: false },
  ],
  typeTraining: [
    { name: "مجاني", value: "مجاني" },
    { name: "مدفوع", value: "مدفوع" },
  ],
  country: [
    { value: "حمص", name: "حمص" },
    { value: "دمشق", name: "دمشق" },
    { value: "حلب", name: "حلب" },
    { value: "دير الزور", name: "دير الزور" },
    { value: "اللاذقية", name: "اللاذقية" },
  ],
  level: [
    { value: "غير دارس", name: "غير دارس" },
    { value: "ابتدائي", name: "ابتدائي" },
    { value: "اعدادي", name: "اعدادي" },
    { value: "ثانوي عام", name: "ثانوي عام" },
    { value: "ثانوي مهني", name: "ثانوي مهني" },
    { value: "ثانوي تجاري", name: "ثانوي تجاري" },
    { value: "جامعة", name: "جامعة" },
    { value: "معهد", name: "معهد" },
    { value: "ماجستير", name: "ماجستير" },
    { value: "دكتوراه", name: "دكتوراه" },
  ],
  subjectType: [
    { value: "أخرى", name: "أخرى" },
    { value: "ابتدائي", name: "ابتدائي" },
    { value: "اعدادي", name: "اعدادي" },
    { value: "ثانوي عام", name: "ثانوي عام" },
    { value: "ثانوي مهني", name: "ثانوي مهني" },
    { value: "ثانوي تجاري", name: "ثانوي تجاري" },
    { value: "جامعة", name: "جامعة" },
    { value: "معهد", name: "معهد" },
    { value: "ماجستير", name: "ماجستير" },
    { value: "دكتوراه", name: "دكتوراه" },
  ],
  permission: [
    { value: "user.all", name: "جميع الصلاحيات للمستخدم" },
    { value: "user.interests", name: "اهتمامات المستخدم" },
    { value: "account.update", name: "تحديث الحساب" },
    { value: "account.delete", name: "حذف الحساب" },
    { value: "account.disable", name: "تعطيل الحساب" },
    { value: "account.changePassword", name: "تغيير كلمة مرور الحساب" },
    { value: "account.changePhone", name: "تغيير رقم الموبايل" },
    { value: "account.changeEmail", name: "تغيير البريد الإلكتروني" },
    { value: "account.uploadImage", name: "رفع صورة الحساب" },
    { value: "account.deleteImage", name: "حذف صورة الحساب" },
    { value: "account.getImage", name: "طلب صورة الحساب" },
    { value: "role.create", name: "إنشاء دور" },
    { value: "role.update", name: "تحديث دور" },
    { value: "role.delete", name: "حذف دور" },
    { value: "role.all", name: "جميع صلاحيات الدور" },
    { value: "branch.create", name: "إنشاء فرع" },
    { value: "branch.update", name: "تعديل فرع" },
    { value: "branch.all", name: "جميع صلاحيات الفرع" },
    { value: "employee.add", name: "إضافة موظف" },
    { value: "employee.addInMyBranch", name: "إضافة موظف في فرعي" },
    { value: "employee.update", name: "تعديل موظف" },
    { value: "employee.updateInMyBranch", name: "تعديل موظف في فرعي" },
    { value: "employee.delete", name: "حذف موظف" },
    { value: "employee.deleteInMyBranch", name: "حذف موظف في فرعي" },
    { value: "employee.all", name: "جميع صلاحيات الموظف" },
    { value: "employee.allInMyBranch", name: "جميع صلاحيات الموظف في فرعي" },
  ],
  show: [
    { name: "معاهد", value: "institutes" },
    { name: "موظفين", value: "employees" },
    { name: "أدوار", value: "roles" },
    { name: "إحصائيات", value: "statistics" },
  ],
  permissionIns: [
    { value: "user.all", name: "2جميع الصلاحيات للمستخدم" },
    { value: "user.interests", name: "اهتمامات المستخدم" },
    { value: "account.update", name: "تحديث الحساب" },
    { value: "account.delete", name: "حذف الحساب" },
    { value: "account.disable", name: "تعطيل الحساب" },
    { value: "account.changePassword", name: "تغيير كلمة مرور الحساب" },
    { value: "account.changePhone", name: "تغيير رقم الموبايل" },
    { value: "account.changeEmail", name: "تغيير البريد الإلكتروني" },
    { value: "account.uploadImage", name: "رفع صورة الحساب" },
    { value: "account.deleteImage", name: "حذف صورة الحساب" },
    { value: "account.getImage", name: "طلب صورة الحساب" },
    { value: "role.create", name: "إنشاء دور" },
    { value: "role.update", name: "تحديث دور" },
    { value: "role.delete", name: "حذف دور" },
    { value: "role.all", name: "جميع صلاحيات الدور" },
    { value: "branch.create", name: "إنشاء فرع" },
    { value: "branch.update", name: "تعديل فرع" },
    { value: "branch.all", name: "جميع صلاحيات الفرع" },
    { value: "employee.add", name: "إضافة موظف" },
    { value: "employee.addInMyBranch", name: "إضافة موظف في فرعي" },
    { value: "employee.update", name: "تعديل موظف" },
    { value: "employee.updateInMyBranch", name: "تعديل موظف في فرعي" },
    { value: "employee.delete", name: "حذف موظف" },
    { value: "employee.deleteInMyBranch", name: "حذف موظف في فرعي" },
    { value: "employee.all", name: "جميع صلاحيات الموظف" },
    { value: "employee.allInMyBranch", name: "جميع صلاحيات الموظف في فرعي" },
  ],
  showIns: [
    { name: "إحصائيات المركز", value: "statistics" },
    { name: "الأفرع", value: "branches" },
    { name: "موظفين", value: "employees" },
    { name: "موظفي فرعه فقط", value: "employeesInBranch" },
    { name: "احصائيات الأفرع", value: "branchStatistics" },
    { name: "إحصائيات فرعه فقط", value: "branchStatisticsInBranch" },
    { name: "الدورات", value: "courses" },
    { name: "دورات فرعه فقط", value: "coursesInBranch" },
    { name: "الحسومات", value: "discount" },
    { name: "حسومات فرعه فقط", value: "discountInBranch" },
    { name: "الدفاتر", value: "notebooks" },
    { name: "دفاتر فرعه فقط", value: "notebooksInBranch" },
    { name: "أقساط الطلاب", value: "payments" },
    { name: "أقساط طلاب فرعه فقط", value: "paymentsInBranch" },
    { name: "أجور المعلمين", value: "receipts" },
    { name: "أجور معلمي فرعه فقط", value: "receiptsInBranch" },
    { name: "أدوار", value: "roles" },
    { name: "قاعات", value: "rooms" },
    { name: "قاعات فرعه فقط", value: "roomsInBranch" },
    { name: "طلاب", value: "students" },
    { name: "طلاب فرعه فقط", value: "studentsInBranch" },
    { name: "مواد", value: "subjects" },
    { name: "مواد فرعه فقط", value: "subjectsInBranch" },
    { name: "معلمين", value: "teachers" },
  ],
  courses: [],
  roles: [],
  subjects: [],
  subjectId: [],
  allSubjects: [],
  subjectsObject: {},
  notebooks: [],
  notebookId: [],
  allNotebooks: [],
  notebooksObject: {},
  discounts: [],
  allDiscounts: [],
  discountsObject: {},
  nameBranch: [],
  choosen: [
    { name: "تم اختياره", value: true },
    { name: "لم يتم اختياره", value: false },
  ],
  deleteReason: [
    { name: "طلب الأستاذ", id: 1 },
    { name: "حالة جوية", id: 2 },
  ],
  states: ["مقبول", "غير مقبول", "معلق"],
};

export default selectOptions;
